# Generated by Django 5.2.6 on 2025-09-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_disciplina_alter_solicitacao_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Arquivo comprobatório (opcional)', null=True, upload_to='solicitacoes/%Y/%m/'),
        ),
    ]
