# Generated by Django 5.2.6 on 2025-11-26 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_solicitacao_arquivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='coordenador_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='coordenador_justificativa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='coordenador_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_coordenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='coordenador_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='professor_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='secretaria_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='secretaria_justificativa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='secretaria_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_secretaria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='secretaria_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('coordenador', 'Coordenador'), ('secretaria', 'Secretaria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='solicitacoes.solicitacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
